language: node_js

node_js:
    - "14"

dist: trusty

cache:
    directories:
      - "FrontEnd/node_modules"

before_script:
    - npm install -g @angular/cli

script:
    - cd ./FrontEnd
    - npm install
    - npm run lint
    - npm run build