language: node_js

node_js:
    - "14"

dist: trusty

cache:
    directories:
        - "BackEnd/node_modules"
        - "FrontEnd/node_modules"

before_script:
    - npm install -g @angular/cli

script:
    - cd ./BackEnd
    - npm run lint
    - cd ../FrontEnd
    - npm install
    - npm run lint
    - npm run build