version: "2.3"
services:
  frontend:
    image: jgkawell/angular-todolist-frontend:latest
    container_name: frontend
    build:
      context: ./FrontEnd
      dockerfile: Dockerfile
    ports:
      - "4300:80"
  backend:
    image: jgkawell/angular-todolist-backend:latest
    container_name: backend
    build:
      context: ./BackEnd
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
  db:
    image: jgkawell/angular-todolist-db:latest
    container_name: db
    build:
      context: ./Database
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=todo
      - POSTGRES_PASSWORD=todo
      - POSTGRES_DB=todo
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5